In [19]:
file_name = []
with open('/home/ange/projects/tsn-pytorch20200620/data/ucf101_splits/trainlist01.txt') as f:
    i=0
    while 1:
        i+=1
        line =f.readline()
        line = '_'.join(line.split(' ')[0].split('.')[0].split('/')[1].split('_')[1:])
        print(line)
#         line=line.replace('/','_')
#         print(line)
        #print(type(line))
#         file_name.append(line)
        if line==''or i==3:
            break
        file_name.append(line)
print(len(file_name))
file_name[-1]

ApplyEyeMakeup_g08_c01
ApplyEyeMakeup_g08_c02
ApplyEyeMakeup_g08_c03
2


'ApplyEyeMakeup_g08_c02'

In [12]:
string = file_name[0]
print(string)
string.replace('/','_')

ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01


'ApplyEyeMakeup_v_ApplyEyeMakeup_g08_c01'

In [31]:
with open('/home/ange/projects/temporal-segment-networks/data/ucf101_splits/classInd.txt') as f:
    line_save = []
    while 1:
        line = f.readline()
        #line =line.split(' ')
        if line == '':
            break
        line_save.append(line)
#print(line_save)

In [1]:
# import os
# dirs = os.listdir('/data/ange/ms-tcn/data/ucf101/features/') 
# train_split=[]
# test_split=[]
# for file in dirs:
#     if file.split('_')[0]=='trainlist01':
#         train_split.append(file.split('.')[0]+'.txt')
#     if file.split('_')[0]=='testlist01':
#         test_split.append(file.split('.')[0]+'.txt')
# # print(train_split)
# for i in test_split:
#     print(i)
# #print(test_split)
# save_path = '/data/ange/ms-tcn/data/ucf101/splits'
# print('path exist?',os.path.exists(save_path))
# if not os.path.exists(save_path):
#     os.mkdir(save_path)
# # if not os.path.exists(os.path.join(save_path,'test.split.bundle')):
# #     os.mkdir(os.path.join(save_path,'test.split.bundle'))
# # with open(os.path.join(save_path,'test.split.bundle')) as f:
# #     for i in test_split:
# #         f.write(i)
# if not os.path.isfile(os.path.join(save_path,'test.split.bundle')):
#     os.mknod(os.path.join(save_path,'test.split.bundle'))
    
# if not os.path.isfile(os.path.join(save_path,'train.split.bundle')):
#     os.mknod(os.path.join(save_path,'train.split.bundle'))
    
#os.mkdir()
# with open(os.path.join(save_path,'train.split.bundle'),'a') as f:
#     for i in train_split:
#         f.write(i+'\n')
        
# with open(os.path.join(save_path,'test.split.bundle'),'a') as f:
#     for i in test_split:
#         f.write(i+'\n')
# # print(dirs[0].split('_')[0]) 
# #print(dirs[1:5])

In [55]:
import os
base_path = '/home/ange/projects/tsn-pytorch20200620/ucf101/'
if not os.path.exists(os.path.join(base_path, 'features')):
    os.mkdir(os.path.join(base_path, 'features'))
    print('files created')

In [57]:
# copy many time the label  ms-tcn

import os
#path='/media/l/E/projects/ms-tcn-master1/data/ucf101/groundTruth/'
path = '/data/ange/ms-tcn/data/ucf101/flow_groundTruth/'
files = os.listdir(path)
print(len(files))
print(files[0])
test_list = []  
# for file in files:  # ????????testlist01??????????????????????
#     if file.split('_')[0] == 'testlist01':
#         test_list.append(file)

for file in files:
    with open(os.path.join(path,file)) as f:
        line = f.readlines()
    new_line = 250*line
    with open(os.path.join(path,file),'w') as f:
        f.writelines(new_line)

202
trainlist01_TableTennisShot_g25_c07.txt


In [2]:
# label 1-101 => 0-100
label=[]
action=[]
content=[]
#/data/ange/ms-tcn/data/ucf101/mapping.txt
with open('/data/ange/ms-tcn/data/ucf101/mapping.txt') as f:
    while 1:
        line = f.readline()
        
        if line=='':  # ?line?????????if????
            break 
        line = str(int(line.split(' ')[0])-1)+' '+line.split(' ')[1] 
        content.append(line)
#         print(line)
#         line = line.split(' ')   # ?????????

#         label.append(int(line[0])-1)
#         action.append(line[1])
# print(label)
#print(content)
with open('/data/ange/ms-tcn/data/ucf101/mapping.txt','w') as f:
    f.writelines(content)

In [61]:
# ?groundTruth number label to action label
with open('/data/ange/ms-tcn/data/ucf101/mapping.txt') as f:
    action=[]
    while 1:
        line = f.readline()
        if line == '':
            break
        action.append(line.split(' ')[1])

#         print(line.split(' ')[1])
#     print(action)


groundTruth_files_path = '/data/ange/ms-tcn/data/ucf101/flow_groundTruth/'
groundTruth_files = os.listdir(groundTruth_files_path)
print(len(groundTruth_files))
for groundTruth_file in groundTruth_files:
    with open(os.path.join(groundTruth_files_path,groundTruth_file)) as f:
        new_action=[]
        while 1:
            line =f.readline()
            if len(line)>4:
                print('not nembers')
                break
            if line =='':
                break
            new_action.append(action[int(line)])
    #         print(line)
    #         print(action[int(line)])
    #     print(new_action)

    with open(os.path.join(groundTruth_files_path,groundTruth_file),'w') as f:
        f.writelines(new_action)

202


In [67]:
name = 'lengchuanjiang'
ID = 1910651
year = 26
print('name=%s, ID=%d, year=%d' % (name,ID,year))
with open('/data/ange/ms-tcn/experiment_result.txt', 'a') as f:
            f.writelines('\n\n name=%s, ID=%d, year=%d' % (name,ID,year))
#print("[epoch %d]: epoch loss = %f,   acc = %f" % (epoch + 1, epoch_loss / len(batch_gen.list_of_examples),
#                                                               float(correct)/total))

name=lengchuanjiang, ID=1910651, year=26


In [3]:
with open('/home/ange/projects/temporal-segment-networks/data/ucf101_rgb_val_split_1.txt') as f:
    count =0
    test_name = []
    test_num = []
    lable_origianl = 0
    while 1 :
        count += 1
        line = f.readline()
        if line == '' or count == 10000:
            break
        
        line = line.strip().split(' ')

        label = int(line[2])  #  miss first class action
        if count ==1 :
            test_name.append('_'.join(line[0].split('/')[-1].split('_')[1:]))
            test_num.append(count)
            lable_origianl = label
        if label!= lable_origianl:  # 
            test_name.append('_'.join(line[0].split('/')[-1].split('_')[1:]))
            test_num.append(count)
            lable_origianl = label
            
#     test_name.append('_'.join(line[0].split('/')[-1].split('_')[1:]))  # 
#     test_num.append(count)
            
#         print(line[0])
#         print(label)
    
#     print(test_name)
#     print(test_num)


In [4]:
with open('/home/ange/projects/temporal-segment-networks/data/ucf101_rgb_train_split_1.txt') as f:
    train_name = []
    count_train = 0
    while 1:
        
        line = f.readline()
        if line == '' or count == 10000:
            break
        line = line.strip().split(' ')
        name = '_'.join(line[0].split('/')[-1].split('_')[1:])
        #print(name)
        train_name.append(name)
        
# for i in test_num:
#     print(i)
#     print(train_name[i-1])


In [5]:
import os
# os.rename(srcFile,dstFile)
file_name = []
with open('/home/ange/projects/tsn-pytorch20200620/data/ucf101_splits/trainlist01.txt') as f:
    while 1:
        line =f.readline()
        if line=='':
            break
        line = '_'.join(line.split(' ')[0].split('.')[0].split('/')[1].split('_')[1:])
        file_name.append(line)
#print(file_name)
old_name =[]
for i in test_num[1:]:
#     print(i)
#     print(file_name[i-2])   # 文件存在的文件名需要修改的文件 文件 
    old_name.append(file_name[i-2])
#print(old_name)

In [7]:
import os
# os.rename('/home/ange/new_file (copy)', '/home/ange/new_file')  # rename needn't suffix 
new_name = test_name
#print(new_name)
old_name = old_name
#print(old_name)
base_path = '/data/ange/ms-tcn/data/ucf101/features'
for i in range(len(new_name)):
    old_file_path = os.path.join(base_path,'testlist01_'+old_name[i]+'.npy')
    new_file_path = os.path.join(base_path,'testlist01_'+new_name[i]+'.npy')
    os.rename(old_file_path,new_file_path)
#     print(new_file_path)
   # print(os.path.isfile(old_file_path))
    

IndexError: list index out of range

In [8]:
# for i in range(3,len(new_name)):
#     print(i)

In [155]:
os.rename('/data/ange/ms-tcn/data/ucf101/splits/test.split.bundle', '/data/ange/ms-tcn/data/ucf101/splits/test.split1.bundle')

In [10]:
import torch
a=torch.rand(2,3,4)
print(a)

tensor([[[0.6163, 0.3762, 0.3050, 0.2720],
         [0.9132, 0.7715, 0.0807, 0.9291],
         [0.9540, 0.5385, 0.4709, 0.3136]],

        [[0.9899, 0.8253, 0.0810, 0.4711],
         [0.2305, 0.4289, 0.6148, 0.8971],
         [0.9888, 0.3055, 0.5738, 0.1229]]])


In [16]:
# rename groundTruth
import os
# os.rename('/home/ange/new_file (copy)', '/home/ange/new_file')  # rename needn't suffix 
new_name = test_name
#print(new_name)
old_name = old_name
#print(old_name)
base_path = '/data/ange/ms-tcn/data/ucf101/groundTruth'
for i in range(5,len(new_name)):
#for i in range(5):
    old_file_path = os.path.join(base_path,'testlist01_'+old_name[i]+'.txt')
    new_file_path = os.path.join(base_path,'testlist01_'+new_name[i]+'.txt')
    os.rename(old_file_path,new_file_path)
    print(new_file_path)
   # print(os.path.isfile(old_file_path))

/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BandMarching_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BaseballPitch_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_Basketball_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BasketballDunk_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BenchPress_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_Biking_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_Billiards_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BlowDryHair_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BlowingCandles_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BodyWeightSquats_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_Bowling_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BoxingPunchingBag_g01_c01.txt
/data/ange/ms-tcn/data/ucf101/groundTruth/testlist01_BoxingSpeedBag_g

IndexError: list index out of range

In [14]:
train_name
test_name
old_name
new_name

['ApplyEyeMakeup_g01_c01',
 'ApplyLipstick_g01_c01',
 'Archery_g01_c01',
 'BabyCrawling_g01_c01',
 'BalanceBeam_g01_c01',
 'BandMarching_g01_c01',
 'BaseballPitch_g01_c01',
 'Basketball_g01_c01',
 'BasketballDunk_g01_c01',
 'BenchPress_g01_c01',
 'Biking_g01_c01',
 'Billiards_g01_c01',
 'BlowDryHair_g01_c01',
 'BlowingCandles_g01_c01',
 'BodyWeightSquats_g01_c01',
 'Bowling_g01_c01',
 'BoxingPunchingBag_g01_c01',
 'BoxingSpeedBag_g01_c01',
 'BreastStroke_g01_c01',
 'BrushingTeeth_g01_c01',
 'CleanAndJerk_g01_c01',
 'CliffDiving_g01_c01',
 'CricketBowling_g01_c01',
 'CricketShot_g01_c01',
 'CuttingInKitchen_g01_c01',
 'Diving_g01_c01',
 'Drumming_g01_c01',
 'Fencing_g01_c01',
 'FieldHockeyPenalty_g01_c01',
 'FloorGymnastics_g01_c01',
 'FrisbeeCatch_g01_c01',
 'FrontCrawl_g01_c01',
 'GolfSwing_g01_c01',
 'Haircut_g01_c01',
 'Hammering_g01_c01',
 'HammerThrow_g01_c01',
 'HandStandPushups_g01_c01',
 'HandstandWalking_g01_c01',
 'HeadMassage_g01_c01',
 'HighJump_g01_c01',
 'HorseRace_g01_c0

In [17]:
11000/250

44.0

In [27]:
# multi-dim matrix copy
import torch
# a = torch.rand(2,3)
# print('a',a)
# b = a.repeat(1,2)
# print('b',b)
# c = a.repeat(2,1)
# print('c',c)
# d = torch.mean(a,1)
# print(d)
e = torch.rand(2,3,4)
print(e)
f = torch.mean(e,1).unsqueeze(1)
print(f)
print(f.shape)


tensor([[[0.2592, 0.5768, 0.1806, 0.4328],
         [0.1260, 0.0473, 0.3558, 0.9694],
         [0.3553, 0.7244, 0.4364, 0.0187]],

        [[0.4803, 0.8141, 0.2076, 0.8276],
         [0.1376, 0.0177, 0.8952, 0.6580],
         [0.7548, 0.7059, 0.2327, 0.4213]]])
tensor([[[0.2468, 0.4495, 0.3243, 0.4736]],

        [[0.4575, 0.5126, 0.4452, 0.6356]]])
torch.Size([2, 1, 4])


In [30]:
(0.2592+0.1260+0.3553)/3


0.24683333333333332

In [29]:
0.2592+0.4803

0.7395

In [32]:
a = torch.rand(4,2,8,3)
print(a)
torch.mean(a,3)

tensor([[[[0.2396, 0.1527, 0.5477],
          [0.8940, 0.5533, 0.8794],
          [0.5674, 0.3599, 0.6371],
          [0.3656, 0.1728, 0.5310],
          [0.5720, 0.2047, 0.3163],
          [0.6294, 0.7315, 0.8268],
          [0.2886, 0.1469, 0.6556],
          [0.8050, 0.5791, 0.3000]],

         [[0.9807, 0.4498, 0.3418],
          [0.9638, 0.6742, 0.4622],
          [0.1729, 0.4701, 0.0209],
          [0.7050, 0.3181, 0.9649],
          [0.5425, 0.9631, 0.8917],
          [0.0075, 0.9628, 0.9025],
          [0.1228, 0.4118, 0.0941],
          [0.3265, 0.6540, 0.2554]]],


        [[[0.0060, 0.1999, 0.5864],
          [0.4733, 0.4385, 0.4733],
          [0.4987, 0.5113, 0.4050],
          [0.9999, 0.0889, 0.4027],
          [0.6011, 0.3790, 0.2612],
          [0.5663, 0.9337, 0.7175],
          [0.9754, 0.7924, 0.7744],
          [0.5055, 0.5859, 0.4969]],

         [[0.8055, 0.7165, 0.1419],
          [0.1644, 0.5895, 0.2096],
          [0.6514, 0.7049, 0.8732],
          [0.0447, 0

tensor([[[0.3133, 0.7756, 0.5215, 0.3565, 0.3643, 0.7292, 0.3637, 0.5614],
         [0.5907, 0.7001, 0.2213, 0.6627, 0.7991, 0.6242, 0.2096, 0.4120]],

        [[0.2641, 0.4617, 0.4717, 0.4972, 0.4138, 0.7392, 0.8474, 0.5295],
         [0.5546, 0.3211, 0.7432, 0.4752, 0.3196, 0.4057, 0.3605, 0.4556]],

        [[0.5914, 0.5473, 0.8658, 0.2788, 0.6394, 0.5677, 0.5600, 0.4715],
         [0.4879, 0.9708, 0.3235, 0.6678, 0.3183, 0.4294, 0.5606, 0.3744]],

        [[0.7186, 0.6409, 0.5306, 0.3780, 0.1225, 0.3877, 0.8317, 0.5187],
         [0.2602, 0.5183, 0.3106, 0.2945, 0.5207, 0.3113, 0.4647, 0.6928]]])

In [55]:
  int(int(line[1])/20)

6

In [4]:
file_name = []
class Data:
    pass
video = [Data()]*10000
# with open('/home/ange/projects/temporal-segment-networks/data/ucf101_rgb_val_split_1(less).txt') as f:
with open('/home/ange/projects/temporal-segment-networks/data/ucf101_rgb_val_split_1.txt') as f:
    i=0
    while 1:
        i+=1
        line =f.readline()
#         print(line)
        line = line.strip().split(' ')

#         if int(int(line[1])/20) <= 5:
#             video[i].sample_num = 5
#         elif int(int(line[1])/20) <= 10:
#             video[i].sample_num = 5
#         elif 
#         print(line)
        #line = '_'.join(line.split(' ')[0].split('.')[0].split('/')[1].split('_')[1:])

#         line=line.replace('/','_')
#         print(line)
        #print(type(line))
#         file_name.append(line)
#         print(line)
        if line[0]==''or i==10000:
            print(i-1)
            break
        video[i].path = line[0]
        video[i].frame_num = int(line[1])
        #print(video[i].frame_num)
        video[i].label = line[2]
        video[i].sample_num = int(int(line[1])/20)
        file_name.append(line)
frame = []
print(video[10].frame_num)
for i in range(1,3784):
    frame.append(video[i].frame_num)
print(frame)
# print(video[10].path)
# print(video[10].frame_num)
# print(video[10].label)

3783
199
[199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 

In [5]:
import numpy as np
GPSType=np.dtype({'names':['id','px','py','vx','vy'],'formats':['S32','f','f','f','f']})
Data=np.array([('zero',0.,0.,0,1)]*10,dtype=GPSType)

Data[0]['id']='00'
Data[0]['px']=1.1
Data[0]['py']=1.2
Data[0]['vx']=1.3
Data[0]['vy']=1.4
#Data[1]
Data[1]['id']='01'
Data[1]['px']=2.1
Data[1]['py']=2.2
Data[1]['vx']=2.3
Data[1]['vy']=2.4
print(Data)

[(b'00', 1.1, 1.2, 1.3, 1.4) (b'01', 2.1, 2.2, 2.3, 2.4)
 (b'zero', 0. , 0. , 0. , 1. ) (b'zero', 0. , 0. , 0. , 1. )
 (b'zero', 0. , 0. , 0. , 1. ) (b'zero', 0. , 0. , 0. , 1. )
 (b'zero', 0. , 0. , 0. , 1. ) (b'zero', 0. , 0. , 0. , 1. )
 (b'zero', 0. , 0. , 0. , 1. ) (b'zero', 0. , 0. , 0. , 1. )]


In [5]:
class Data:
    pass
data = [Data()]*5
for i in range(5):
    data[i].pos = str(i)
    data[i].num = i+1
print(data[4].pos)
print(data[3].pos)

4
4


In [7]:
class GPS:
    pass
Data = [GPS()]*2

#Data[0]
Data[0].id='00'
Data[0].px=1.1
Data[0].py=1.2
Data[0].vx=1.3
Data[0].vy=1.4

#Data[1]
Data[1].id='01'
Data[1].px=2.1
Data[1].py=2.2
Data[1].vx=2.3
Data[1].vy=2.4
print(Data[0].id)
print(Data[0].px)
print(Data[1].id)
print(Data[1].px)


01
2.1
01
2.1


In [35]:
class Data(object):
    def __init__(self,pos,num,label):
        self.pos = '/home/ange/projects'
        self.num = 200
        self.label =0

data = [Data('a',1,2)]*5
data[0].count = 4
print(data[1].count)
data[0].count = 5
print(data[1].count)

4
5


In [8]:
round(0.9)

1

In [9]:
99/100

0.99

In [10]:
99/100

0.99

In [65]:
#import torch
import numpy as np
end=163
segments = 2
a = list(range(1,163))
step = int(end/(segments*5))
print(step)
start = np.random.randint(1,step,[1]).item()
print(start)
b = np.linspace(start,end,segments*5,endpoint=False).astype(int)
b
#b.tolist()

16
5


array([  5,  20,  36,  52,  68,  84,  99, 115, 131, 147])

In [63]:
np.random.randint(1,10,[1]).item()

9

In [81]:
import numpy as np
rgb_score = np.load('/home/ange/projects/tsn-ms-pytorch/tsn-pytorch20200722/resnet_rgb_score_seg5_0720.npz', encoding='bytes')

labels = rgb_score['labels']
print(labels)
scores = rgb_score['scores']
print(scores)
rgb_score.files

[  0   0   0 ... 100 100 100]
[[array([[[ 2.14283676e+01,  1.55786133e+01,  7.87386119e-01,
         -7.41724133e-01,  7.48213351e-01,  7.14027405e-01,
         -4.46715355e-01, -6.99292850e+00, -5.51434088e+00,
         -4.94613028e+00, -5.59103298e+00, -9.60744843e-02,
          1.17008734e+01,  8.20254612e+00,  1.34477985e+00,
         -1.01390302e+00, -4.20145702e+00,  1.75227904e+00,
         -2.83916354e+00,  5.30673933e+00,  7.09465623e-01,
          2.92675877e+00, -2.30455184e+00, -3.16126204e+00,
          5.79797459e+00, -5.09981537e+00,  2.95768690e+00,
         -2.56804442e+00,  6.32565618e-01,  4.29160023e+00,
         -2.15114188e+00,  4.06285238e+00, -3.28704691e+00,
          1.17104206e+01, -2.66387463e+00, -5.17987680e+00,
          6.14860582e+00, -2.19689459e-01, -1.97574461e+00,
         -5.37819564e-01, -3.82138371e+00, -5.09730864e+00,
          5.55390604e-02, -1.37829876e+00, -3.07237387e+00,
         -8.86618316e-01,  1.99951577e+00, -1.75993001e+00,
        

['labels', 'scores']

In [89]:
a=[]
a.append('123')
a.append(56)
a.append([1,2,3])
a.append([[1,2,3],[4,5,6]])
a


['123', 56, [1, 2, 3], [[1, 2, 3], [4, 5, 6]]]